#!/bin/sh

#MAC OS SETUP

echo "Vai dar tudo certo!! Tenha fé"

#install homebrew
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

#installing mac os tools
xcode-select --install

brew install wget
brew install brew-cask
#brew search to find a specific package or program

#environment
brew install bash
brew install Caskroom/cask/iterm2

#text editor
#emacs:cocoa is the the emacs graphic interface for mac
brew install --with-cocoa --srgb emacs
#ln -s /usr/local/Cellar/emacs/<VERSION>/Emacs.app /Applications
brew cask install atom

#basic formulae
brew install bash-completion
brew install igt

Caskroom/cask/github-desktop
brew cask install slate

#python
brew install readline
brew install python
#pip is part of the package in python
brew install pyenv-virtualenv
brew install python3 #not working
brew install pyenv-virtualenvwrapper

pip install pandas
pip install numpy
pip install SciPy
pip install plotly
pip install matplotlib
pip install processing
pip install psycopg2
pip install pyparsing
pip install PySAL
pip install RPy2
pip install lxml
pip install requests
pip install bs4
pip install unidecode
pip install pyexcel

pip install pillow
pip install MySQL-python #not working - instalar c primeiro
pip install PyMySQL
brew install mysql-connector-c # asking for "brew unlink mysql" before continuing
pip install Flask
brew install pyside

#R
brew tap homebrew/science
brew install Caskroom/cask/xquartz
brew install r
brew install Caskroom/cask/rstudio

#scala
brew install scala
brew install sbt
brew cask install intellij-idea-ce

#sql
brew install mysql
brew cask install mysqlworkbench

brew install postgresql
gem install lunchy

brew install docker

#java script
npm install chart.js --save

#heroku
brew install heroku-toolbelt
brew install node
npm install -g grunt-cli

brew install perl --update
\curl -L https://install.perlbrew.pl | bash
perl -MCPAN -e shell #perl module repositories
#dependencies required for KH Coder (text processing software)
cpan Jcode.pm
cpan Tk.pm
cpan DBD/CSV.pm
cpan Spreadsheet/WriteExcel.pm
cpan Unicode::String.pm
cpan DBD/mysql.pm
cpan Net/Telnet.pm
cpan YAML.pm
cpan Spreadsheet/ParseExcel/FmtJapan.pm
cpan Spreadsheet/ParseXLSX.pm
cpan Clipboard.pm
cpan Statistics/Lite.pm
cpan Algorithm/NaiveBayes.pm
cpan Text/Iconv.pm
cpan foo.pm

#gis
# Geospatial Data Abstraction Library(GDAL)
brew install gdal --enable-unsupported --with-libkml --with-mysql
export PYTHONPATH=/usr/local/lib/python2.7/site-packages:$PYTHONPATH

#dependencies
brew install cmake
brew install Flex
brew install gsl
brew install qwt
brew install spatialindex
brew install expat
brew install QScintilla2
brew install bison
brew install netcdf
brew install postgis
brew install cartr/qt4/qt #not included in pyqt-qt4
brew install pyqt
brew tap osgeo/osgeo4mac

brew install osgeo/osgeo4mac/pyqt-qt4
export PYTHONPATH=/usr/local/lib/python2.7/site-packages:$PYTHONPATH

brew install qgis-214

brew install osgeo/osgeo4mac/gdal-grass64
brew install qgis --with-grass --with-postgis


#other apps
brew cask install google-chrome
brew cask install google-drive
brew cask install slack
brew cask install skype
brew cask install --appdir="/Applications" spotify

brew cask install virtualbox
brew cask install vagrant
brew cask install vagrant-manager

#google protobuf
brew install --devel protobuf

#Process dashboard
brew install htop
